# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GrademainwindowVIEW.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 450)
        MainWindow.setMinimumSize(QtCore.QSize(300, 450))
        MainWindow.setMaximumSize(QtCore.QSize(300, 450))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input_grades = QtWidgets.QLineEdit(self.centralwidget)
        self.input_grades.setGeometry(QtCore.QRect(30, 100, 251, 21))
        self.input_grades.setObjectName("input_grades")
        self.button_submit = QtWidgets.QPushButton(self.centralwidget)
        self.button_submit.setGeometry(QtCore.QRect(80, 130, 131, 32))
        self.button_submit.setObjectName("button_submit")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(80, 10, 131, 20))
        self.label_title.setObjectName("label_title")
        self.label_instructions = QtWidgets.QLabel(self.centralwidget)
        self.label_instructions.setGeometry(QtCore.QRect(30, 30, 261, 41))
        self.label_instructions.setObjectName("label_instructions")
        self.label_output = QtWidgets.QLabel(self.centralwidget)
        self.label_output.setGeometry(QtCore.QRect(20, 170, 261, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_output.setFont(font)
        self.label_output.setText("")
        self.label_output.setObjectName("label_output")
        self.line_numbstudents = QtWidgets.QLineEdit(self.centralwidget)
        self.line_numbstudents.setGeometry(QtCore.QRect(30, 60, 251, 21))
        self.line_numbstudents.setObjectName("line_numbstudents")
        self.label_inputgrades = QtWidgets.QLabel(self.centralwidget)
        self.label_inputgrades.setGeometry(QtCore.QRect(30, 80, 251, 16))
        self.label_inputgrades.setObjectName("label_inputgrades")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Grademainwindow"))
        self.button_submit.setText(_translate("MainWindow", "Calculate Grades"))
        self.label_title.setText(_translate("MainWindow", "GRADE CALCULATOR"))
        self.label_instructions.setText(_translate("MainWindow", "Number Of Grades"))
        self.label_inputgrades.setText(_translate("MainWindow", "Enter Grades (seperated by spaces )"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
