# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Votemainwindow_View.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 300)
        MainWindow.setMinimumSize(QtCore.QSize(500, 300))
        MainWindow.setMaximumSize(QtCore.QSize(500, 300))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title1 = QtWidgets.QLabel(self.centralwidget)
        self.title1.setGeometry(QtCore.QRect(130, 10, 231, 21))
        self.title1.setObjectName("title1")
        self.title2 = QtWidgets.QLabel(self.centralwidget)
        self.title2.setGeometry(QtCore.QRect(140, 30, 201, 16))
        self.title2.setObjectName("title2")
        self.Yes_button = QtWidgets.QRadioButton(self.centralwidget)
        self.Yes_button.setGeometry(QtCore.QRect(250, 70, 51, 20))
        self.Yes_button.setObjectName("Yes_button")
        self.buttonGroup_1 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_1.setObjectName("buttonGroup_1")
        self.buttonGroup_1.addButton(self.Yes_button)
        self.No_button = QtWidgets.QRadioButton(self.centralwidget)
        self.No_button.setGeometry(QtCore.QRect(330, 70, 51, 20))
        self.No_button.setObjectName("No_button")
        self.buttonGroup_1.addButton(self.No_button)
        self.question1_label = QtWidgets.QLabel(self.centralwidget)
        self.question1_label.setGeometry(QtCore.QRect(10, 70, 221, 16))
        self.question1_label.setObjectName("question1_label")
        self.question2_label = QtWidgets.QLabel(self.centralwidget)
        self.question2_label.setGeometry(QtCore.QRect(10, 110, 251, 16))
        self.question2_label.setObjectName("question2_label")
        self.input_collegeID = QtWidgets.QLineEdit(self.centralwidget)
        self.input_collegeID.setGeometry(QtCore.QRect(270, 110, 141, 21))
        self.input_collegeID.setObjectName("input_collegeID")
        self.question3_label = QtWidgets.QLabel(self.centralwidget)
        self.question3_label.setGeometry(QtCore.QRect(10, 150, 141, 16))
        self.question3_label.setObjectName("question3_label")
        self.Uno_button = QtWidgets.QRadioButton(self.centralwidget)
        self.Uno_button.setGeometry(QtCore.QRect(180, 150, 61, 20))
        self.Uno_button.setObjectName("Uno_button")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.Uno_button)
        self.UNL_button = QtWidgets.QRadioButton(self.centralwidget)
        self.UNL_button.setGeometry(QtCore.QRect(250, 150, 61, 20))
        self.UNL_button.setObjectName("UNL_button")
        self.buttonGroup_2.addButton(self.UNL_button)
        self.label_output = QtWidgets.QLabel(self.centralwidget)
        self.label_output.setGeometry(QtCore.QRect(10, 180, 441, 31))
        self.label_output.setText("")
        self.label_output.setObjectName("label_output")
        self.button_submit = QtWidgets.QPushButton(self.centralwidget)
        self.button_submit.setGeometry(QtCore.QRect(310, 210, 100, 32))
        self.button_submit.setObjectName("button_submit")
        self.Add_button = QtWidgets.QPushButton(self.centralwidget)
        self.Add_button.setGeometry(QtCore.QRect(10, 210, 100, 32))
        self.Add_button.setObjectName("Add_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 24))
        self.menubar.setObjectName("menubar")
        self.menuvoting_system = QtWidgets.QMenu(self.menubar)
        self.menuvoting_system.setObjectName("menuvoting_system")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuvoting_system.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "voting system"))
        self.title1.setText(_translate("MainWindow", "Which school is better? UNO or UNL?"))
        self.title2.setText(_translate("MainWindow", "(must be a UNO or UNL Student)"))
        self.Yes_button.setText(_translate("MainWindow", "Yes"))
        self.No_button.setText(_translate("MainWindow", "No"))
        self.question1_label.setText(_translate("MainWindow", "Are You A UNO or UNL Student?"))
        self.question2_label.setText(_translate("MainWindow", "What Is Your College Id? (cant vote twice)"))
        self.question3_label.setText(_translate("MainWindow", "Which School is better?"))
        self.Uno_button.setText(_translate("MainWindow", "UNO"))
        self.UNL_button.setText(_translate("MainWindow", "UNL"))
        self.button_submit.setText(_translate("MainWindow", "Submit"))
        self.Add_button.setText(_translate("MainWindow", "Add Vote"))
        self.menuvoting_system.setTitle(_translate("MainWindow", "voting system"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
